SUPPORTED_FEDORA_RELEASE=44
PROJECT_ID=fedora-sway-quickshell-demo
PROJECT_ALLOWED_REPOS_REGEX='^(fedora|updates|fedora-cisco-openh264)(-[a-z0-9_-]+)?$'
CODEX_CLI_VERSION=0.147.0
CODEX_CLI_INTEGRITY='sha512-EQLEXecAG2ptxI7UpBMo2TR/ga5596/c/OsYF/0LoUDh5JANZ7IoGqlzBEWbuEVQ76JePIbtTW/ihCkp1a7Z3w=='
